### ISSUE TITLE
Allow passing slice instead of vertex pointer

### ISSUE THREAD

**Issue by DavidPeicho** [jbikker/tinybvh#31]
Hi!

Thanks again for the library 👍

It would be great to allow to have an overload of:

```cpp
void Build(bvhslice<bhvec4> vertices, const unsigned primCount );
```

With `bvhslice` a struct to allow strided access to `bvhvec4`. It's especially useful in a codebase that mixes rasterization, and might have strided buffers.

Don't mind giving it a shot if it's something other people find interesting!

**Comment by jbikker** [comment]
Good idea, and I think it can be done without a performance impact; fragment creation wouldn't mind a different step size through the data, as long as vertices are 16 byte (that does matter). Maybe have a third parameter 'stride' that defaults to '16' (in bytes) or simply '1' (in bvhvec4's)?

**Comment by DavidPeicho** [comment]
Subjectively I like having a slice type, since this can easily be passed around. That being said, since I am wrapping the library in Rust, I can do that part on my side and it could be a third parameter yes

**Comment by jbikker** [comment]
I am not familiar with slice types, I did check up on std::slice but that does not appear to be what you refer to. This custom slice type you refer to, would it be possible to have two access points for each builder, one that takes this slice type, and one that takes the original arguments, which would trivially forward the call using a slice with stride 1?

**Comment by DavidPeicho** [comment]
Was thinking of something simpler to not rely on the `std`. Example:

```cpp
struct Slice {
     const char* ptr;
     uint8_t stride;
}
```

Depending on whether you accept it to be templated or not, this can be improved, especially construction and reading elements.

I think that should be backward compatible? A rough example of what it would look like:

```cpp
void Build(Slice slice, unsigned primCount) {
    verts = slice;
}

void Build(const bvhvec4* verts, unsigned primCount) {
    return Build({
        .ptr = reinterpret_cast<const char>(verts),
        .stride = sizeof(bvhvec4)
    }, primCount)
}
```

**Comment by jbikker** [comment]
That looks good. I think an implementation without templating would be best here.

**Comment by jbikker** [comment]
I will await your PR. :)

**Comment by DavidPeicho** [comment]
There is no "unit" testing setup right? What would be the best to test this?

**Comment by jbikker** [comment]
There is testing for the main branch, I am not sure why this is not enabled
for the dev one. I will investigate.

**Comment by jbikker** [comment]
PR merged!
