### ISSUE TITLE
The need for CI

### ISSUE THREAD

**Issue by eloj** [jbikker/tinybvh#6]
I think it's going to be almost impossible to maintain this and not break it for 'alternative' platforms/compilers, without some sort of CI.

I have some limited experience setting up github workflows, and would be willing to make an attempt, if such a PR would be acceptable (after the usual review of course).

**Comment by jbikker** [comment]
Jefferson Amstutz just made a PR for this. This is outside my field of expertise but since his additions do not involve modifications to tiny_bvh.h I blindly (but gratefully) accepted it.
