### ISSUE TITLE
Using custom allocation functions broke with the API rework

### ISSUE THREAD

**Issue by jkoenen** [jbikker/tinybvh#66]
Thanks a lot for this great piece of software - After the last version I unfortunately have a crash because the library doesn't use the provided context to override the allocations functions anymore.

~~~
tinybvh::BVH4_CPU blas;
blas.context = myContext;
blas.Build( vertices, triangleCount );
~~~

This internally will create more temporary Bvh structures which use the default memory context. Either the context needs to be copied, or maybe change the api to always pass the context into functions that require memory operations. 

I fixed it for my by setting the context member of both BVH structs on the way.

**Comment by DavidPeicho** [comment]
Wouldn't it make sense to have a way to set a global allocator instead? Or do you build BVH with different allocators?

**Comment by jkoenen** [comment]
I would prefer to pass it as a parameter because it simplifies the situation in multi-threaded situations (Where different threads potentially use different heaps)

**Comment by jbikker** [comment]
This should be fixed in the dev branch now: The context that you pass to each of the specialized / derived layouts is now propagated to the intermediate formats. It's a simple fix, but it is a bit hard for me to verify; can you confirm it works properly? After that I will close this issue.

**Comment by jkoenen** [comment]
Yes, that works for me - thank you for the quick fix

**Comment by jbikker** [comment]
Thanks for confirming; case closed.
