### ISSUE TITLE
please make releases

### ISSUE THREAD

**Issue by tigrazone** [jbikker/tinybvh#70]
for just download and run exes.
w/o compiling or so

**Comment by jbikker** [comment]
What would be the use case for this?
Tinybvh is not intended as an end-user product, and the code examples are provided only to demonstrate how it could be integrated in your own programs.

**Comment by tigrazone** [comment]
Yes I need these code examples compiled

**Comment by jbikker** [comment]
I'm sorry, closing this issue; tinybvh really isn't a stand-alone product.
