### ISSUE TITLE
Wrong link to Bittner et al. paper

### ISSUE THREAD

**Issue by szellmann** [jbikker/tinybvh#72]
This link here points to the wrong paper: https://github.com/jbikker/tinybvh/blob/main/README.md?plain=1#L108
Maybe replace it with this link to the author version? https://dspace.cvut.cz/bitstream/handle/10467/15603/2013-Fast-Insertion-Based-Optimization-of-Bounding-Volume-Hierarchies.pdf;jsessionid=19C0D5B7A5C67B32E3693137911DEAFA?sequence=1

**Comment by jbikker** [comment]
Thank you. This is now fixed in the dev branch.
