### ISSUE TITLE
2 minor fixes for compiling gpu sample under Linux..

### ISSUE THREAD

**Issue by oscarbg** [jbikker/tinybvh#73]
Hi,
compiling tiny_bvh_gpu.cpp sample:
g++ -std=c++20 -mavx -Ofast tiny_bvh_gpu.cpp -o tiny_bvh_gpu -I /usr/include/CL -lX11 -lOpenCL
gets 2 errors on Linux:

1)tiny_ocl.h:658:22: error: ‘_stricmp’ was not declared in this scope; did you mean ‘strncmp’?

2)tiny_bvh_gpu.cpp:73:9: error: reference to ‘generate’ is ambiguous
tiny_bvh_gpu.cpp:161:9: error: reference to ‘generate’ is ambiguous
tiny_bvh_gpu.cpp:162:9: error: reference to ‘generate’ is ambiguous

first one fixed:
```
-               if (!_stricmp( file, loadedKernels[i]->sourceFile ))
+               if (!strcasecmp( file, loadedKernels[i]->sourceFile ))

```
second one I replace variable name "generate" with "generate2" in the 3 cases is in code and it works..
it's due to some "thing" in GCC 14:
/usr/include/c++/14/bits/stl_algo.h:4344:5: note: candidates are: ‘template<class _FIter, class _Generator> constexpr void std::generate(_FIter, _FIter, _Generator)’
 4344 |     generate(_ForwardIterator __first, _ForwardIterator __last,

so please rename "generate" to another name..

tested that fix and works ok on RTX 4070..

**Comment by jbikker** [comment]
Thank you for that. Is that "-lOpenCL" using some package on Linux? I suppose you can't simply use the Windows library?
Changes have been made; they should now be available in the dev branch.
