### ISSUE TITLE
Dot Product for Baldwin and Weber Triangle intersection

### ISSUE THREAD

**Issue by benanil** [jbikker/tinybvh#75]
This is used soo many times:

float transS = T2.x * O.x + T2.y * O.y + T2.z * O.z + T2.w;
float transD = T2.x * D.x + T2.y * D.y + T2.z * D.z;

we can do it with 2 dot products

float transS = dot(T2.xyz,  O) + T2.w;
float transD = dot(T2.xyz,  D);

It might be faster

**Comment by jbikker** [comment]
For the current three big vendors this should not make a difference: Kernel code is 'scalarized' and then executed in SIMT fashion (e.g., 32 threads running the same scalar code). See:
https://www.reddit.com/r/OpenCL/comments/8gloes/opencl_preferred_and_native_vector_width/
One could argue that the dot product code is more clear though. Not sure about that.
